### ISSUE TITLE
Circular view path []: would dispatch back to the current handler URL

### ISSUE THREAD

**Issue by charmingfst** [apache/incubator-dubbo-ops#107]
![image](https://user-images.githubusercontent.com/10810285/45337791-59362580-b5bc-11e8-869b-89be20e6836f.png)
具体服务者点进去就报下面错误
![image](https://user-images.githubusercontent.com/10810285/45337700-efb61700-b5bb-11e8-9b4c-b556b398281c.png)
使用maven3.3.9打包

**Comment by nzomkxia** [comment]
please try the new version
