### ISSUE TITLE
improve yaml editor

### ISSUE THREAD

**Issue by nzomkxia** [apache/incubator-dubbo-ops#108]
the service governance use yaml instead of table in old version, the choice of editor is CodeMirror, is there any better solution?  
you can refer to routing rule page as a template

**Comment by majinkai** [comment]
How about [Ace](https://ace.c9.io/).

**Comment by majinkai** [comment]
I added ace-editor into `components/AceEditor.vue`(Actual cases refer to access control module.), here is usage:

```html
<template>
  <ace-editor v-model="content" :config="aceConfig" />
</template>

<script>
import AceEditor from '@/components/AceEditor'

export default {
  components: {
    AceEditor
  },
  data: () => ({
    content: '',
    aceConfig: {}
  })
}
</script>
```

Default config:
```javascript
{
  width: '100%',
  height: '300px',
  lang: 'yaml',
  theme: 'monokai',
  readonly: false,
  fontSize: 14,
  tabSize: 2
}
```
