### ISSUE TITLE
新版本dubbo-ops使用dubbo.registry.address=redis://XXXX:6379 无法启动

### ISSUE THREAD

**Issue by zxf527** [apache/incubator-dubbo-ops#113]
是否还没实现redis作为注册中心

**Comment by nzomkxia** [comment]
are you using redis as registry center? can you provide the exception during startup

**Comment by zhuSilence** [comment]
> are you using redis as registry center? can you provide the exception during startup

When I started dubbo-admin with redis registry center I can't find providers and consumers. Did I do something wrong or It's not supported yet?

**Comment by zhuSilence** [comment]
> > are you using redis as registry center? can you provide the exception during startup
> 
> When I started dubbo-admin with redis registry center I can't find providers and consumers. Did I do something wrong or It's not supported yet?

Ok, it's done, It's my mistake. But when I stop provides or consumers, It's still displayed on the page. There isn't a heartbeat to check alive service?
