### ISSUE TITLE
problem with accessing the fonts

### ISSUE THREAD

**Issue by laodaobazi** [apache/incubator-dubbo-ops#118]
https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons
这个字体样式不翻墙访问不到哟

**Comment by nzomkxia** [comment]
![image](https://user-images.githubusercontent.com/1183397/45859473-1da61300-bd95-11e8-8e20-77d32587fb18.png)  
the ip seems in Beijing, do you have a problem with accessing the fonts？

**Comment by nzomkxia** [comment]
#136

**Comment by nzomkxia** [comment]
I've fixed it, please update to the latest version and try again
