### ISSUE TITLE
java -jar 运行打包的jar包，404

### ISSUE THREAD

**Issue by qidai77777** [apache/incubator-dubbo-ops#121]
mvn clean package打包dubbo-admin后，启动jar包  能正常启动，zookeeper中也能看到对应的dubbo节点
但是访问 localhost:8080 后提示404

**Comment by nzomkxia** [comment]
please try the `develop` branch，now we are working on that

**Comment by qidai77777** [comment]
> please try the `develop` branch，now we are working on that

Do you have any solution?

**Comment by nzomkxia** [comment]
after mvn clean package, start service with `mvn --projects dubbo-admin-backend spring-boot:run
`

**Comment by qidai77777** [comment]
# build
mvn clean install

# run
mvn --projects dubbo-admin-backend spring-boot:run

And then the error is found

`[ERROR] [ERROR] Could not find the selected project in the reactor: dubbo-admin-
backend @
[ERROR] Could not find the selected project in the reactor: dubbo-admin-backend
-> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MavenExecution
Exception`

**Comment by qidai77777** [comment]
> after mvn clean package, start service with `mvn --projects dubbo-admin-backend spring-boot:run`

build
mvn clean install

run
mvn --projects dubbo-admin-backend spring-boot:run

And then the error is found

[ERROR] [ERROR] Could not find the selected project in the reactor: dubbo-admin- backend @ [ERROR] Could not find the selected project in the reactor: dubbo-admin-backend -> [Help 1] [ERROR] [ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit ch. [ERROR] Re-run Maven using the -X switch to enable full debug logging. [ERROR] [ERROR] For more information about the errors and possible solutions, please rea d the following articles: [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MavenExecution Exception

**Comment by nzomkxia** [comment]
witch branch are you working on? and please make sure you are under `incubator-dubbo-ops` directory

**Comment by qidai77777** [comment]
> which branch are you working on? and please make sure you are under `incubator-dubbo-ops` directory

It's OK,thx
