### ISSUE TITLE
develop是不是还是个半成品

### ISSUE THREAD

**Issue by yohole** [apache/incubator-dubbo-ops#128]
develop分支的前后端版本，是不是还是个半成品？太多问题了，启动之后，各种问题，跑不通

**Comment by majinkai** [comment]
develop版本目前还在持续开发中，是最新的代码，请使用JDK8+，最新的提交基本都没什么问题，是可以跑通的，功能还在一步步实现功能，具体启动步骤如下：

1. 用develop分支Clone代码
2. 修改dubbo-admin-backend/src/resources/application.properties中的zk地址，指向你的注册中心
3. 执行mvn clean package
4. 执行mvn --projects dubbo-admin-backend spring-boot:run
5. 访问http://localhost:8080

如发现问题，麻烦您给我们提交issues，谢谢 :)

**Comment by luyanfeng** [comment]
怎么管理同一个服务的不通分组

**Comment by nzomkxia** [comment]
@luyanfeng 目前的服务搜索页面，有`group`属性的展示，同一个服务的不同分组会区别开来
