### ISSUE TITLE
您好，使用redis做为注册中心，但redis需要密码访问时dubbo.registry.address该如何配置？

### ISSUE THREAD

**Issue by cnhnnyzhy** [apache/incubator-dubbo-ops#13]
您好，使用redis做为注册中心，但redis需要密码访问时dubbo.registry.address该如何配置？

**Comment by zonghaishang** [comment]
@cnhnnyzhy try <dubbo:registry address="redis address" password="your password"/>

**Comment by beiwei30** [comment]
this has been fixed by 4c95cfe9424377c827d0b181d042f40105042cf7

**Comment by beiwei30** [comment]
4c95cfe9424377c827d0b181d042f40105042cf7 should fix this.
