### ISSUE TITLE
打开页面后直接进入了，没有要求输入密码，进来什么都没有。zookeeper地址配置正确了，

### ISSUE THREAD

**Issue by chenfangzhi123** [apache/incubator-dubbo-ops#134]
![tim 20181010151842](https://user-images.githubusercontent.com/19573164/46719211-ee056f00-cc9f-11e8-889e-4769f1c79f0a.png)

进来就是这个样子，什么信息都没有
![123](https://user-images.githubusercontent.com/19573164/46719219-f2ca2300-cc9f-11e8-997f-23d78623eb17.png)

点击设置，退出按钮jun均没有反应。
可否发一个教程？或者弄一个稳定版？

**Comment by Joker1995** [comment]
![image](https://user-images.githubusercontent.com/12840349/53156152-a3a2e000-35f9-11e9-8434-3c9d516eb6e0.png)
I still can access the monitor without username and password

**Comment by kezhenxu94** [comment]
> ![image](https://user-images.githubusercontent.com/12840349/53156152-a3a2e000-35f9-11e9-8434-3c9d516eb6e0.png)
> I still can access the monitor without username and password

@Joker1995 There is no authorization yet, see #204 and #210

**Comment by Joker1995** [comment]
> > ![image](https://user-images.githubusercontent.com/12840349/53156152-a3a2e000-35f9-11e9-8434-3c9d516eb6e0.png)
> > I still can access the monitor without username and password
> 
> @Joker1995 There is no authorization yet, see #204 and #210

![image](https://user-images.githubusercontent.com/12840349/53308826-3afc8180-38df-11e9-91ad-4667bf429dcb.png)
There has some problem with this configuration
