### ISSUE TITLE
无法加载 “https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons”

### ISSUE THREAD

**Issue by blackdancers** [apache/incubator-dubbo-ops#136]
https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons
加载失败，页面布局异常

**Comment by nzomkxia** [comment]
can you try `ping fonts.googleapis.com` and paste the result here?

**Comment by blackdancers** [comment]
![image](https://user-images.githubusercontent.com/4956686/47065262-f23c0a00-d214-11e8-873e-07a4f5bcb258.png)

**Comment by nzomkxia** [comment]
thanks, I'll figure this out

**Comment by nzomkxia** [comment]
I've fixed it, please update to the latest version and try again
