### ISSUE TITLE
话说右上角那几个按钮一直点不动正常吗

### ISSUE THREAD

**Issue by mwq0106** [apache/incubator-dubbo-ops#150]
我跑出界面了，但是编译的时候有错误，右上角的几个按钮怎么点都不管用是没项目做完还是我自己这边的问题，如果是没做完是不是老版的项目功能更加全面一些，然后建议使用老的项目？

**Comment by nzomkxia** [comment]
1. 具体的编译错误请发一下  
2. 右上角的按钮，全屏是可以用的，其他的设置，通知和用户信息还没有做，但是这三个按钮，**老版本都是没有的**，目前和老版本相比，服务查询和服务治理的功能都是完善的，登录功能还没有，可以使用新版本。

**Comment by VanXD** [comment]
新版本是不是没有monitor了?readme里也没看到相关统计的介绍?

**Comment by majinkai** [comment]
新版本会提供全新的monitor，请持续关注，谢谢

**Comment by soonway** [comment]
新版本里面关于配置的部分说明不够。

里面的几个配置项新增的分别是做什么用的？
dubbo.registry.group=dubbo
dubbo.configcenter=zookeeper://127.0.0.1:2181
dubbo.apollo.token=e16e5cd903fd0c97a116c873b448544b9d086de9
dubbo.apollo.appId=test
dubbo.apollo.env=dev
dubbo.apollo.cluster=default
dubbo.apollo.namespace=dubbo

问题：
1、生产用application-production.properties，开发用application.properties这个吗？
2、dubbo.configcenter是不是应该写成dubbo.config.center？
3、后面dubbo.apollo相关的项可以不用吗？分别是做什么用？

**Comment by htynkn** [comment]
右上角那几个按钮功能这一版本还不会发布，已经删除 https://github.com/apache/incubator-dubbo-ops/commit/23049f5db205d3ac9b0685e2a784c230ea507d07

@soonway 你提到的点，我另外开了一个issue https://github.com/apache/incubator-dubbo-ops/issues/213
