### ISSUE TITLE
启动dubbo-admin-backend无法看到服务

### ISSUE THREAD

**Issue by qiudaozhang** [apache/incubator-dubbo-ops#160]
启动admin后台项目可以访问，但是看不到服务，使用zookeeper可以查看到，添加分组也试过了，还是无法看到，请问能说下是什么原因吗？

**Comment by nzomkxia** [comment]
目前的逻辑，不会默认展示所有的服务了，请使用搜索，如果不知道服务名 直接点击`Search`按钮，搜索全量服务

**Comment by qiudaozhang** [comment]
> 目前的逻辑，不会默认展示所有的服务了，请使用搜索，如果不知道服务名 直接点击`Search`按钮，搜索全量服务

我按照提示搜索比如 com.xx.service.DemoService:1.0。
结果显示Network error, please check your network settings!

**Comment by qiudaozhang** [comment]
> 服务是什么部署的？如果是前后端分开部署(前端用npm启动，后端启动spring boot应用)请使用develop maven profile，详情请见[这里](https://github.com/apache/incubator-dubbo-ops#development-setup)

ubuntu上面clone的工程，zookeeper配置的是单个节点，按照要求在incubator-dubbo-ops根目录下
mvn clean package -Pproduction
然后
mvn --projects dubbo-admin-backend spring-boot:run
访问8080，然后没有东西，zookeeper命令下是能看到的。

**Comment by nzomkxia** [comment]
> > 服务是什么部署的？如果是前后端分开部署(前端用npm启动，后端启动spring boot应用)请使用develop maven profile，详情请见[这里](https://github.com/apache/incubator-dubbo-ops#development-setup)
> 
> ubuntu上面clone的工程，zookeeper配置的是单个节点，按照要求在incubator-dubbo-ops根目录下
> mvn clean package -Pproduction
> 然后
> mvn --projects dubbo-admin-backend spring-boot:run
> 访问8080，然后没有东西，zookeeper命令下是能看到的。

Network error，看一下浏览器报什么错

**Comment by 89333367** [comment]
我这里也是一样的，启动都成功，zookeeper也有相应信息，页面上就是看不到服务

**Comment by 89333367** [comment]
页面报错
http://localhost:8080/api/dev/service?pattern=service+name&filter= net::ERR_CONNECTION_REFUSED
但是我是再服务器上启动的，应该是192.168开头才对

**Comment by 89333367** [comment]
我在本地启动，就能看到服务了。是不是页面写死了访问的是localhost

**Comment by nzomkxia** [comment]
是的 默认是本地部署，本地访问，可以在`components/http-common.js`里面修改，这个我放到文档里

**Comment by u91win** [comment]
修改  dubbo-admin-frontend/src/components/http-common.js   里面的 baseURL ， 重新打包可以运行： 

let instance = axios.create({
  **baseURL: 'http://192.168.2.230:8080/api/dev'**
})

**Comment by nzomkxia** [comment]
> 修改 dubbo-admin-frontend/src/components/http-common.js 里面的 baseURL ， 重新打包可以运行：
> 
> let instance = axios.create({
> **baseURL: 'http://your-ip-address:8080/api/dev'**
> })

谢谢，这块我们会体现在文档里面

**Comment by qiudaozhang** [comment]
> 修改 dubbo-admin-frontend/src/components/http-common.js 里面的 baseURL ， 重新打包可以运行：
> 
> let instance = axios.create({
> **baseURL: 'http://your-ip-address:8080/api/dev'**
> })

请问你是在windows下打包运行的吗？需要修改其它参数吗？

**Comment by qiudaozhang** [comment]
> > 修改 dubbo-admin-frontend/src/components/http-common.js 里面的 baseURL ， 重新打包可以运行：
> > let instance = axios.create({
> > **baseURL: 'http://your-ip-address:8080/api/dev'**
> > })
> 
> 谢谢，这块我们会体现在文档里面

你好，我将这里的IP修改为了我部署的zookeeper的机器的IP地址，依然是http://localhost:8080/api/dev/service?pattern=service+name&filter= net::ERR_CONNECTION_REFUSED，这又是什么情况呢？

**Comment by qiudaozhang** [comment]
> > > 修改 dubbo-admin-frontend/src/components/http-common.js 里面的 baseURL ， 重新打包可以运行：
> > > let instance = axios.create({
> > > **baseURL: 'http://your-ip-address:8080/api/dev'**
> > > })
> > 
> > 
> > 谢谢，这块我们会体现在文档里面
> 
> 你好，我将这里的IP修改为了我部署的zookeeper的机器的IP地址，依然是http://localhost:8080/api/dev/service?pattern=service+name&filter= net::ERR_CONNECTION_REFUSED，这又是什么情况呢？



> > 修改 dubbo-admin-frontend/src/components/http-common.js 里面的 baseURL ， 重新打包可以运行：
> > let instance = axios.create({
> > **baseURL: 'http://your-ip-address:8080/api/dev'**
> > })
> 
> 谢谢，这块我们会体现在文档里面

显示错误为：ServiceSearch.vue:153 Uncaught (in promise) TypeError: Cannot read property 'data' of undefined
    at ServiceSearch.vue:153 ， 我已经修改过IP地址了。

**Comment by qiudaozhang** [comment]
> 是的 默认是本地部署，本地访问，可以在`components/http-common.js`里面修改，这个我放到文档里

已经解决了，多谢。

**Comment by cookerzhu** [comment]
> > 是的 默认是本地部署，本地访问，可以在`components/http-common.js`里面修改，这个我放到文档里
> 
> 已经解决了，多谢。

我的也报错：Uncaught (in promise) TypeError: Cannot read property 'data' of undefined ，该怎么解决

**Comment by nzomkxia** [comment]
配置已经做过修改，现在无论是本地还是其他机器部署，前后端分开还是一起部署，都不需要修改任何地址和参数了，请更新代码后再试一下，谢谢

**Comment by huixw** [comment]
一块部署成功了，后端数据返回了，但是页面上不展示，前端的bug？
