### ISSUE TITLE
可以看到提供者，看不到消费者的信息。

### ISSUE THREAD

**Issue by xp-git** [apache/incubator-dubbo-ops#162]
![image](https://user-images.githubusercontent.com/24203113/47414854-99d0b380-d7a4-11e8-96e8-97521ebb66a7.png)
消费者测试消费的时候看不到消费者的信息，为啥。
![image](https://user-images.githubusercontent.com/24203113/47414788-6e4dc900-d7a4-11e8-9278-4362418a1d47.png)

**Comment by nzomkxia** [comment]
有消费者消费过这个provider么？

**Comment by xp-git** [comment]
嗯。有的。改了一个地方，就显出出来了。
看了之前issue的回答。

后台查询逻辑存在问题，路径/api/service/detail的后台方法不应该将配置的application作为条件查询，
因为消费者和生产者所配置的applicatioin名称不一样，
将org.apache.dubbo.admin.controller.ServiceController文件的serviceDetail方法中providerService.findByAppandService(app, service)改成providerService.findByService(service)，
同时将consumerService.findByAppandService(app, service)改成consumerService.findByService(service)即可正常显示。

**Comment by xp-git** [comment]
https://github.com/apache/incubator-dubbo-ops/issues/98

这里有说到了。

**Comment by nzomkxia** [comment]
已经fix了，请试一下

**Comment by gyjx** [comment]
这个bug在最新版本修复了吗？为什么我git下来的develop依然看不到consumer信息？

**Comment by No-sleeping** [comment]
> 这个bug在最新版本修复了吗？为什么我git下来的develop依然看不到consumer信息？

你好，请问解决了么，我这里也是没有消费者。
这里还有个问题 我的dubbo是2.7.8的 也缺少元数据。
