### ISSUE TITLE
dubbo-monitor 2.8.3 如何获取统计数据以扩展自定义报表

### ISSUE THREAD

**Issue by LinoMay** [apache/incubator-dubbo-ops#174]
目前使用的 dubbo-monitor 2.8.3版本，目前想基于已有的统计数据出报表，主要从调用量、平均响应时间、调用时间段等维度统计，当前只能指定单个服务去查看统计数据，无法汇总所有服务的统计信息，不知道该版本是否支持扩展，以获取数据用于出服务预警统计报表。
望解答，谢谢。

**Comment by nzomkxia** [comment]
dubbo monitor的功能会合并到当前版本的dubbo ops里面，基于metrics实现，你提到的这些维度都会统计到，汇总服务统计信息这个功能我们会考虑，请关注后续版本 谢谢

**Comment by LinoMay** [comment]
> dubbo monitor的功能会合并到当前版本的dubbo ops里面，基于metrics实现，你提到的这些维度都会统计到，汇总服务统计信息这个功能我们会考虑，请关注后续版本 谢谢

感谢！
