### ISSUE TITLE
请问dubbo-monitor统计页面的箭头“-->"表示的是什么意思？

### ISSUE THREAD

**Issue by LinoMay** [apache/incubator-dubbo-ops#176]
如题。查过很多资料，包括官方文档，都没有说明箭头左右两边的数字分别代表什么意思。烦请解答一下，谢谢。

**Comment by LinoMay** [comment]
> 路由规则
> 
> http://dubbo.apache.org/zh-cn/docs/user/demos/routing-rule.html
> 
> 配置规则
> 
> http://dubbo.apache.org/zh-cn/docs/user/demos/config-rule.html

不好意思，我说的不是这两个箭头诶，我说的是类似这样的箭头
[https://static.oschina.net/uploads/space/2018/0313/135538_EB1B_3383385.jpg](url)

**Comment by majinkai** [comment]
左边是
consumer，右边是provider

**Comment by LinoMay** [comment]
> provider

哦，感谢终于解答我的疑惑了！那再请教一下，如何理解消费者和提供者统计数量不一致的情况？尤其是consumer是0的情况，还有一种情况是count(consumer) > count(provider)。烦请指导一下。

**Comment by majinkai** [comment]
有可能是因为consumer或者provider端没有开启monitor

**Comment by LinoMay** [comment]
> 有可能是因为consumer或者provider端没有开启monitor

嗯，我也有考虑过这个方面，但是不合理啊，在同一个服务的方法列表中，有些consumer是有数字的，有些又是0，与您说的这种方法相违背啊。如果说没有开启的话，应该全部是0才对。

**Comment by majinkai** [comment]
老版的monitor已经不再维护了，我也没有仔细去看细节代码，新版monitor会在这里重新实现，望持续关注

**Comment by LinoMay** [comment]
> 老版的monitor已经不再维护了，我也没有仔细去看细节代码，新版monitor会在这里重新实现，望持续关注

好的，谢谢！

**Comment by Hakon1014** [comment]
你好，为什么左边的QPS图标会经常一条直线了？什么意思的？

**Comment by meifu2027** [comment]
> 你好，为什么左边的QPS图标会经常一条直线了？什么意思的？

最好能有图，截图说明下看看，这样有点抽象。

**Comment by Hakon1014** [comment]
![dubbo-monitor-qps](https://user-images.githubusercontent.com/24516334/54890840-20b9c180-4ee6-11e9-829f-0d5fb6b5d787.png)
你好，就是图中标识的部分。

**Comment by meifu2027** [comment]
直线表示这段时间没有请求，没有消费者要请求这个提供者
