### ISSUE TITLE
[功能疑问] filter为空时不执行搜索

### ISSUE THREAD

**Issue by wolf427** [apache/incubator-dubbo-ops#179]
不懂为什么把搜索逻辑改了，之前都是进主页了点搜索就可以看到所有服务，现在必须要输入服务名才可以搜出结果。看了代码，是故意让filter为空时返回false。感觉还是之前的逻辑合理。

**Comment by nzomkxia** [comment]
现在的搜索支持wildcard，输入 * 可以搜索全量服务，我加一个提示
