### ISSUE TITLE
新版本没老版本好用

### ISSUE THREAD

**Issue by Python-IBM** [apache/incubator-dubbo-ops#187]
我觉得新版本没最早的老版本好用，现在搜啥都要用输入名字才能搜出来，页面交互看得没老版本直观，只是换了个css和页面，用户体验不太好，建议沿用老版本的操作体验。

**Comment by nzomkxia** [comment]
如果需要全量搜索 可以输入 * 提示上面有。
具体老版本哪些交互觉得方便的，可以提出来

**Comment by Python-IBM** [comment]
希望像老版那样，点application时，显示所有的application name，而不是整个service；点ip时，显示所有的机器，而不是整个service。新版没有显示该application所在的group，这样无法确定现在看到的服务是否属于这个group内。

**Comment by nzomkxia** [comment]
1. 不会默认显示全量数据  
2. 新版本的查询都是服务维度的，服务会归属于某一个应用  
3.在有配置的情况下，服务查询会显示某个服务所在的组别，你说的application所在的group是指什么？

**Comment by nzomkxia** [comment]
> application所在的group是指比如userServer服务暴露在dev group，就要显示对应的group信息为dev。但目前是没显示这个应用暴露的服务是在哪个group。

组别是服务粒度的概念，不是应用粒度的，如果一个应用暴露多个服务，分属多个组别，那这个应用就没法对应到一个组别上了

**Comment by gyjx** [comment]
老版本 应用里每个应用是消费者，提供者。新版本没有这个功能，建议加上！
![image](https://user-images.githubusercontent.com/20329819/72240017-cda02f00-361d-11ea-894a-76be7f72eb02.png)
