### ISSUE TITLE
怎么没有dubbo-monitor模块了？

### ISSUE THREAD

**Issue by Python-IBM** [apache/incubator-dubbo-ops#191]
项目里怎么没有dubbo-monitor模块？

**Comment by nzomkxia** [comment]
Dubbo monitor不再作为一个单独的工程，后续会集成到Dubbo admin里面，采用metrics来做信息采集

**Comment by Python-IBM** [comment]
请问会在哪个版本里实现?能透露下吗？到时我留意下

**Comment by nzomkxia** [comment]
应该会在一月份或者二月份的版本里面

**Comment by Python-IBM** [comment]
我现在基于开源的dubbo-monitor-simple去跑监控，把源码的dubbo版本改成2.6.3了，消费者跟提供者的配置文件里都加了<dubbo:monitor protocol="registry"/>，但还是不显示charts和statistics，消费端和提供端一直报com.alibaba.dubbo.rpc.RpcException: No provider available from registry 192.168.10.111:2181 for service com.alibaba.dubbo.monitor.MonitorService on consumer 192.168.10.89 use dubbo version 2.6.3，MonitorService在老版本的dubbo-admin有显示的，请问是哪的问题？
