### ISSUE TITLE
使用  mvn clean package  时报错

### ISSUE THREAD

**Issue by SkyGoto** [apache/incubator-dubbo-ops#202]
求助:
第一次尝试 
 用 `mvn clean package ` 时报了以下错误,不知道如何解决,求帮助,谢谢

[INFO] Installing node version v9.11.1
[INFO] Unpacking /home/ubuntu/.m2/repository/com/github/eirslett/node/9.11.1/node-9.11.1-linux-x64.tar.gz into /home/ubuntu/dubbo_admin/incubator-dubbo-ops/dubbo-admin-frontend/node/tmp
[INFO] Copying node binary from /home/ubuntu/dubbo_admin/incubator-dubbo-ops/dubbo-admin-frontend/node/tmp/node-v9.11.1-linux-x64/bin/node to /home/ubuntu/dubbo_admin/incubator-dubbo-ops/dubbo-admin-frontend/node/node
[INFO] Extracting NPM
[INFO] Installed node locally.
[INFO] 
[INFO] --- frontend-maven-plugin:1.6:npm (npm install) @ dubbo-admin-frontend ---
[INFO] Running 'npm install' in /home/ubuntu/dubbo_admin/incubator-dubbo-ops/dubbo-admin-frontend
[WARNING] npm WARN deprecated browserslist@2.11.3: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
[WARNING] npm WARN deprecated bfj-node4@5.3.1: Switch to the `bfj` package for fixes and new features!
[WARNING] npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
[WARNING] npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
[INFO] 
[INFO] > uglifyjs-webpack-plugin@0.4.6 postinstall /home/ubuntu/dubbo_admin/incubator-dubbo-ops/dubbo-admin-frontend/node_modules/webpack/node_modules/uglifyjs-webpack-plugin
[INFO] > node lib/post_install.js
[INFO] 
[ERROR] npm notice created a lockfile as package-lock.json. You should commit this file.
[WARNING] npm WARN ajv-errors@1.0.1 requires a peer of ajv@>=5.0.0 but none is installed. You must install peer dependencies yourself.
[WARNING] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
[WARNING] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
[ERROR] 
[INFO] added 1267 packages in 32.48s
[INFO] 
[INFO] --- frontend-maven-plugin:1.6:npm (npm run build) @ dubbo-admin-frontend ---
[INFO] Running 'npm run build' in /home/ubuntu/dubbo_admin/incubator-dubbo-ops/dubbo-admin-frontend
[INFO] 
[INFO] > dubbo-admin-frontend@1.0.0 build /home/ubuntu/dubbo_admin/incubator-dubbo-ops/dubbo-admin-frontend
[INFO] > node build/build.js
[INFO] 
[ERROR] Killed
[ERROR] npm ERR! code ELIFECYCLE
[ERROR] npm ERR! errno 137
[ERROR] npm ERR! dubbo-admin-frontend@1.0.0 build: `node build/build.js`
[ERROR] npm ERR! Exit status 137
[ERROR] npm ERR! 
[ERROR] npm ERR! Failed at the dubbo-admin-frontend@1.0.0 build script.
[ERROR] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[ERROR] 
[ERROR] npm ERR! A complete log of this run can be found in:
[ERROR] npm ERR!     /home/ubuntu/.npm/_logs/2018-12-16T10_06_37_619Z-debug.log
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] dubbo-admin ........................................ SUCCESS [  1.896 s]
[INFO] dubbo-admin-frontend ............................... FAILURE [01:12 min]
[INFO] dubbo-admin-backend ................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:15 min
[INFO] Finished at: 2018-12-16T18:06:37+08:00
[INFO] Final Memory: 18M/45M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.6:npm (npm run build) on project dubbo-admin-frontend: Failed to run task: 'npm run build' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 137 (Exit value: 137) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :dubbo-admin-frontend

**Comment by SkyGoto** [comment]
什么修改建议吗 , 不会是换系统把...不太切合实际

**Comment by majinkai** [comment]
你把os,jdk的版本发一下，明天试试

**Comment by TeddyTsui** [comment]
[https://github.com/bluesmoon/node-geoip/issues/72](url)
尝试分配更多内存？

**Comment by SkyGoto** [comment]
好像是这样的 , 之前是直接跑在云服务器上,没有关注内存信息, 我在本地新建一个虚拟机测试一下 的确是内存的问题,在高峰期甚至会达到近3G, 多谢帮助,谢谢

![system](https://user-images.githubusercontent.com/32897640/50077454-6ac44480-021f-11e9-8e94-3102c944d12b.png)
