### ISSUE TITLE
velocity报错问题

### ISSUE THREAD

**Issue by objcoding** [apache/incubator-dubbo-ops#223]
本地启动没问题，打包上传到CentOS7服务器启动成功，访问首页报这个错误：
ResourceManager : unable to find resource 'error.vm' in any resource loader.
请问是不是velocity找不到error.vm？如果是，应该怎么配置？
期待大神解答一下，挺急的。

**Comment by nzomkxia** [comment]
请使用develop分支部署，目前的新版本在这个分支上

**Comment by objcoding** [comment]
@nzomkxia 这个分支是前后端分离的分支吧

**Comment by nzomkxia** [comment]
> @nzomkxia 这个分支是前后端分离的分支吧

是的，velocity过于陈旧，spring boot技术体系中已不再维护，目前的版本基于`develop`分支

**Comment by objcoding** [comment]
@nzomkxia 好吧，感谢大佬解答，我研究一下新版。

**Comment by nzomkxia** [comment]
> @nzomkxia 好吧，感谢大佬解答，我研究一下新版。

新版本的部署在README中有，不管在IDE还是命令行，都是部署spring boot应用的标准流程，前端都不需要单独部署，应该可以满足你的要求

**Comment by objcoding** [comment]
@nzomkxia 你应该还要考虑一点，服务器可能只有Java环境，根本没有安装git和maven，这时候本地打包jar，将你们的前端依赖也打包进来，这时候由于本地与服务器环境不一样导致问题的出现，参考一下dubbo-admin出现的问题就是环境不一致导致出错了，还有一点，既然一个控制台搞那么多东西，还不如直接再写个Dockfile，再弄个docker环境运行。

**Comment by nzomkxia** [comment]
已在README中增加了`java -jar`启动方式的说明
