### ISSUE TITLE
不建议前后端分离

### ISSUE THREAD

**Issue by objcoding** [apache/incubator-dubbo-ops#224]
这个只是一个控制台，没必要前后端分离吧，而且前后端分离增加了部署工作，基于springboot打个jar包运行就得了，又不是什么大项目，完全没必要。
如果一定要前后端分离，那么也请一定要维护基于springboot不分离的分支，表示不想折腾，而且现在dubbo-admin也有bug，我已经提了issues，望大佬们过目一下问题。

**Comment by nzomkxia** [comment]
前后端分离是为了开发的便利，以及抽象出接口。部署的时候，可以分开部署，也可以按照spirng boot项目一期打包部署，请看一下`develop`分支的README：https://github.com/apache/incubator-dubbo-ops/blob/develop/README_ZH.md#%E7%94%9F%E4%BA%A7%E7%8E%AF%E5%A2%83%E9%85%8D%E7%BD%AE   
之前基于velocity的master分支不再维护，请运行develop分支
