### ISSUE TITLE
dubbo-admin-backend 工程是不是缺少注册地址配置项

### ISSUE THREAD

**Issue by hrsstd** [apache/incubator-dubbo-ops#229]
ConfigCenter 类里的${dubbo.registry.address:} 缺少配置。

我clone下来之后启动，总会提示如下错误：
`Caused by: org.apache.dubbo.admin.common.exception.ConfigurationException: Either configcenter or registry address is needed
	at org.apache.dubbo.admin.config.ConfigCenter.getRegistry(ConfigCenter.java:107) ~[classes/:na]`
只有当我在application里添加缺少的配置，才可以正常启动？

请问这个是我个人问题还是 忽略了什么？

**Comment by hrwhat** [comment]
ConfigCenter 类里的${dubbo.registry.address:}  注意最后有一个冒号。。。
这个冒号要去掉，要不然肯定找不到配置项

**Comment by nzomkxia** [comment]
> ConfigCenter 类里的${dubbo.registry.address:} 注意最后有一个冒号。。。
> 这个冒号要去掉，要不然肯定找不到配置项

这个冒号是对的，冒号后面代表默认值， 参考：https://www.baeldung.com/spring-value-annotation

**Comment by nzomkxia** [comment]
配置说明链接：  https://github.com/apache/incubator-dubbo-ops/wiki/Dubbo-Admin%E9%85%8D%E7%BD%AE%E8%AF%B4%E6%98%8E

**Comment by hrwhat** [comment]
> > ConfigCenter 类里的${dubbo.registry.address:} 注意最后有一个冒号。。。
> > 这个冒号要去掉，要不然肯定找不到配置项
> 
> 这个冒号是对的，冒号后面代表默认值， 参考：https://www.baeldung.com/spring-value-annotation

不好意思，没仔细看。。。。

**Comment by nzomkxia** [comment]
I've add dubbo.registry.address back, and log some warning when this config is activated
