### ISSUE TITLE
 Error creating bean ....

### ISSUE THREAD

**Issue by blackdancers** [apache/incubator-dubbo-ops#230]
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'accessesController' defined in file [E:\code\dubbo-all\incubator-dubbo-ops-new\dubbo-admin-backend\target\classes\org\apache\dubbo\admin\controller\AccessesController.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'routeServiceImpl': Unsatisfied dependency expressed through field 'registry'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'getRegistry' defined in class path resource [org/apache/dubbo/admin/config/ConfigCenter.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.dubbo.registry.Registry]: Factory method 'getRegistry' threw exception; nested exception is java.lang.ArrayIndexOutOfBoundsException: 1

**Comment by hrsstd** [comment]
I strongly recommend  that in application.properties add the old config : registry.address ，otherwise a lot of people don't understand.After all, now can't be run this boot .

**Comment by nzomkxia** [comment]
> I strongly recommend that in application.properties add the old config : registry.address ，otherwise a lot of people don't understand.After all, now can't be run this boot .

good advice, I'll add this back

**Comment by nzomkxia** [comment]
I've add `dubbo.registry.address` back, and log some warning when this config is activated

**Comment by hrsstd** [comment]
Thank you for your acceptance
