### ISSUE TITLE
mvn clean package报错

### ISSUE THREAD

**Issue by PennHan** [apache/incubator-dubbo-ops#237]
错误信息如下：

[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.6:install-node-and-npm (install node and npm) on project dubbo-admin-frontend: Execution install node and npm of goal com.github.eirslett:frontend-mave
n-plugin:1.6:install-node-and-npm failed: A required class was missing while executing com.github.eirslett:frontend-maven-plugin:1.6:install-node-and-npm: org/apache/http/protocol/HttpContext
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>com.github.eirslett:frontend-maven-plugin:1.6
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/F:/repository/com/github/eirslett/frontend-maven-plugin/1.6/frontend-maven-plugin-1.6.jar
[ERROR] urls[1] = file:/F:/repository/com/github/eirslett/frontend-plugin-core/1.6/frontend-plugin-core-1.6.jar
[ERROR] urls[2] = file:/F:/repository/org/codehaus/jackson/jackson-mapper-asl/1.9.13/jackson-mapper-asl-1.9.13.jar
[ERROR] urls[3] = file:/F:/repository/org/codehaus/jackson/jackson-core-asl/1.9.13/jackson-core-asl-1.9.13.jar
[ERROR] urls[4] = file:/F:/repository/org/apache/commons/commons-compress/1.5/commons-compress-1.5.jar
[ERROR] urls[5] = file:/F:/repository/org/tukaani/xz/1.2/xz-1.2.jar
[ERROR] urls[6] = file:/F:/repository/commons-io/commons-io/1.3.2/commons-io-1.3.2.jar
[ERROR] urls[7] = file:/F:/repository/org/apache/commons/commons-exec/1.3/commons-exec-1.3.jar
[ERROR] urls[8] = file:/F:/repository/org/apache/httpcomponents/httpclient/4.5.1/httpclient-4.5.1.jar
[ERROR] urls[9] = file:/F:/repository/org/codehaus/plexus/plexus-utils/3.0.22/plexus-utils-3.0.22.jar
[ERROR] urls[10] = file:/F:/repository/javax/enterprise/cdi-api/1.0/cdi-api-1.0.jar
[ERROR] urls[11] = file:/F:/repository/com/google/guava/guava/10.0.1/guava-10.0.1.jar
[ERROR] urls[12] = file:/F:/repository/com/google/code/findbugs/jsr305/1.3.9/jsr305-1.3.9.jar
[ERROR] urls[13] = file:/F:/repository/org/sonatype/sisu/sisu-guice/3.1.0/sisu-guice-3.1.0-no_aop.jar
[ERROR] urls[14] = file:/F:/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar
[ERROR] urls[15] = file:/F:/repository/org/eclipse/sisu/org.eclipse.sisu.inject/0.0.0.M2a/org.eclipse.sisu.inject-0.0.0.M2a.jar
[ERROR] urls[16] = file:/F:/repository/asm/asm/3.3.1/asm-3.3.1.jar
[ERROR] urls[17] = file:/F:/repository/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar
[ERROR] urls[18] = file:/F:/repository/org/apache/maven/plugin-tools/maven-plugin-annotations/3.2/maven-plugin-annotations-3.2.jar
[ERROR] urls[19] = file:/F:/repository/org/sonatype/plexus/plexus-build-api/0.0.7/plexus-build-api-0.0.7.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR]
[ERROR] -----------------------------------------------------
[ERROR] : org.apache.http.protocol.HttpContext
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :dubbo-admin-frontend

错误是找不到org/apache/http/protocol/HttpContext，但是我有这个类啊，并且我试过删除repository里org\apache\httpcomponents并重新引用，没起作用。

maven版本：3.5.2
node版本：10.15.0
npm版本：6.5.0

**Comment by nzomkxia** [comment]
我这里无法重现，网上搜了一下有这个问题，大部分都是清空maven仓库修复的，可以试一下清除~/.m2的内容和IDE缓存，mvn clean  之后 重新编译一下

**Comment by PennHan** [comment]
已经解决了，是仓库的问题，是我用了我们公司的maven私服，里面的包有问题导致的，换成阿里仓库地址，再清空repository下指定包，重新导入即可。
