### ISSUE TITLE
打包失败

### ISSUE THREAD

**Issue by binarySortTree** [apache/incubator-dubbo-ops#24]
命令行进入incubator-dubbo-ops-master目录，然后执行mvn package，结果显示打包失败：
![20180407164745](https://user-images.githubusercontent.com/29702355/38453136-7449c1b0-3a83-11e8-890f-e5f08d879db4.png)

加上-X选项后，出错信息如下：
![20180407164840](https://user-images.githubusercontent.com/29702355/38453174-ec28782a-3a83-11e8-8ede-c407f4f2edf7.png)

请问一下，该怎么解决？

我的环境：
maven:3.5.0
jdk:1.8.0_162  64位，
win7

**Comment by nzomkxia** [comment]
please try the new dubbo ops
