### ISSUE TITLE
Could not find artifact org.apache.dubbo:dubbo:jar:2.6.5 in nexus-aliyun

### ISSUE THREAD

**Issue by ravencoo** [apache/incubator-dubbo-ops#243]
The dubbo.jar  in my local repertory ，How to solve the problem... [ERROR] Failed to execute goal on project dubbo-admin-backend: Could not resolve dependencies for project org.apache:dubbo-admin-backend:jar:0.0.1-SNAPSHOT: Could not find artifact org.apache.dubbo:dubbo:jar:2.6.5 in nexus-aliyun (http://maven.aliyun.com/nexus/content/groups/public) -> [Help 1]

**Comment by nzomkxia** [comment]
this dubbo version does not exist, dubbo 2.6.x's group id is com.alibaba.dubbo,
