### ISSUE TITLE
请问这个项目是dubbo admin 和monitor的升级版吗?

### ISSUE THREAD

**Issue by gclsoft** [apache/incubator-dubbo-ops#260]
dubbo admin 和monitor的项目怎么在github找不到了?

**Comment by sunbufu** [comment]
这个项目是 dubbo admin

**Comment by nzomkxia** [comment]
> dubbo admin 和monitor的项目怎么在github找不到了?

原来的dubbo admin和monitor是本项目的`master`分支，当前的默认分支是`develop`，目前暂时只有admin的功能，monitor会在后面加上
