### ISSUE TITLE
在Linux服务器上部署,前后端运行成功。但通过地址访问不到页面。

### ISSUE THREAD

**Issue by MutualExclusion** [apache/incubator-dubbo-ops#266]
![image](https://user-images.githubusercontent.com/26239970/51508174-208e3e80-1e2f-11e9-9362-52a12139ac99.png)
![image](https://user-images.githubusercontent.com/26239970/51508198-3b60b300-1e2f-11e9-999f-d220470cccdb.png)
远程服务器CentOS,安全组开放端口8080,8081,前后台均运行成功。多次关闭重启均访问不到前台页面

**Comment by nzomkxia** [comment]
是在本地浏览器访问远程页面么？

**Comment by MutualExclusion** [comment]
是的，由于不熟悉vue。所以不清楚config/index.js的作用，所以搞了好久。




在2019年01月29日 22:01，min 写道：

是在本地浏览器访问远程页面么？

**Comment by nzomkxia** [comment]
远程服务器上是前后端分离部署的？

**Comment by MutualExclusion** [comment]
不是，同在一台服务器部署的。已经运行成功了，并且外网能够访问到了。

**Comment by nzomkxia** [comment]
谢谢，我看一下是否需要在文档里说明这个配置

**Comment by MutualExclusion** [comment]
哈哈，感觉我这个是新手问题。因为对前端vue一点都不懂。而大多数的教学基本上都是在本地运行，本地访问；所以只查询dubbo的相关文档并没有好的建议，最后查询了vue的相关文档才解决。
