### ISSUE TITLE
registry到同一个address，不同的group时，无法同时获取多个group的数据

### ISSUE THREAD

**Issue by nevin9939** [apache/incubator-dubbo-ops#278]
`<dubbo:registry address="${dubbo.address}" group="test" timeout="20000" />`
`<dubbo:registry address="${dubbo.address}" group="dubbo" timeout="20000" />`
registry到同一个address，不同的group时，无法同时获取test和dubbo的数据，只能加载配置文件中指明的admin.registry.group=test下的数据

**Comment by nzomkxia** [comment]
#198

**Comment by nzomkxia** [comment]
see apache/incubator-dubbo-ops#198, I'll add multi registry support in the future
