### ISSUE TITLE
dubbo monitor打包失败

### ISSUE THREAD

**Issue by jlovedragon** [apache/incubator-dubbo-ops#28]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project dubbo-monitor-simple: Compilation failure: Compilation failure: 
[ERROR] /Users/river/Study/incubator-dubbo-ops/dubbo-monitor-simple/src/main/java/com/alibaba/dubbo/monitor/simple/container/JettyContainer.java:[55,18] 无法访问org.mortbay.component.LifeCycle
[ERROR]   找不到org.mortbay.component.LifeCycle的类文件
[ERROR] /Users/river/Study/incubator-dubbo-ops/dubbo-monitor-simple/src/main/java/com/alibaba/dubbo/monitor/simple/container/JettyContainer.java:[60,50] 无法访问org.mortbay.component.AbstractLifeCycle
[ERROR]   找不到org.mortbay.component.AbstractLifeCycle的类文件
[ERROR] /Users/river/Study/incubator-dubbo-ops/dubbo-monitor-simple/src/main/java/com/alibaba/dubbo/monitor/simple/container/JettyContainer.java:[69,15] 无法访问org.mortbay.util.Attributes
[ERROR]   找不到org.mortbay.util.Attributes的类文件
[ERROR] /Users/river/Study/incubator-dubbo-ops/dubbo-monitor-simple/src/main/java/com/alibaba/dubbo/monitor/simple/container/JettyContainer.java:[72,19] 找不到符号
[ERROR]   符号:   方法 start()
[ERROR]   位置: 类型为org.mortbay.jetty.Server的变量 server
[ERROR] -> [Help 1]

mvn_version:3.5.3
jdk:1.8.0_151 64位
macos

**Comment by beiwei30** [comment]
The build succeeds on my laptop:

```sh
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] dubbo-ops .......................................... SUCCESS [  0.159 s]
[INFO] dubbo-admin ........................................ SUCCESS [ 30.247 s]
[INFO] dubbo-monitor-simple ............................... SUCCESS [ 20.462 s]
[INFO] dubbo-registry-simple .............................. SUCCESS [  0.850 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```

It looks like your jetty dependency is corrupted, pls. wipe out jetty from your local maven repository and try again.
