### ISSUE TITLE
配置管理的做用是什么？

### ISSUE THREAD

**Issue by mtdp** [apache/incubator-dubbo-ops#282]
dev分支上菜单中的“配置管理”的作用是什么？用他来做什么，如果我使用nacos做注册中心及配置管理，是不是功能重叠了，谢谢。

**Comment by nzomkxia** [comment]
稍后会有一篇介绍博客说明，主要是修改在配置中心里面的dubbo全局配置和应用配置，对应的配置文件是`dubbo.properties`，可以在nacos的控制台操作。做这个功能的主要目的是有些用zookeeper的同学，没有对应的控制台界面，需要在命令行操作，不太方便

**Comment by xue2lang** [comment]
@nzomkxia 请问关于这个配置管理的 博客 有了吗？可否发一下地址
