### ISSUE TITLE
服务测试功能的服务搜索优化建议

### ISSUE THREAD

**Issue by yuxiao97** [apache/incubator-dubbo-ops#285]
在服务测试功能模块，目前搜索服务名只能全路径，建议支持全文匹配查询。

**Comment by nzomkxia** [comment]
@yuxiao97 谢谢，第二个版本会增加，另外考虑增加从服务搜索到服务的测试的链接

**Comment by nzomkxia** [comment]
@yuxiao97 等这个功能实现了再关闭好了~

**Comment by kezhenxu94** [comment]
> @yuxiao97 谢谢，第二个版本会增加，另外考虑增加从服务搜索到服务的测试的链接

这个PR添加了"从服务搜索到服务的测试的链接"以及抽取一些国际化字符串
