### ISSUE TITLE
Auto Release with Travis-CI

### ISSUE THREAD

**Issue by kezhenxu94** [apache/incubator-dubbo-ops#289]
Travis-CI can package and release a [GitHub release](https://github.com/apache/incubator-dubbo-ops/releases), including the commit message as release log, on specific condition such as specific tag, branch and others.

**Comment by ralf0131** [comment]
I don't think it is possible, as an Apache project, any release made should be proved by the PPMC. The GitHub release is not recommended way to publish release as an Apache project.

**Comment by kezhenxu94** [comment]
> as an Apache project, any release made should be proved by the PPMC

Thanks for pointint this out
