### ISSUE TITLE
mvn clean package 打包报错

### ISSUE THREAD

**Issue by SFlora** [apache/incubator-dubbo-ops#291]
![2019-02-03 143733](https://user-images.githubusercontent.com/11220892/52173565-cfccfd00-27c1-11e9-9838-bf147612bda2.png)

在个人电脑和服务器上打包都个错误。试过清理maven库，没有解决问题

**Comment by sunbufu** [comment]
请检查下是否可以直接链接到 <https://repository.apache.org>，国内建议配置 [阿里源](https://maven.aliyun.com) 使用。

**Comment by SFlora** [comment]
![2019-02-03 155032](https://user-images.githubusercontent.com/11220892/52174181-7073ea80-27cb-11e9-9e30-7fddec33950b.png)

@nzomkxia A new error has been encountered

**Comment by biyuhao** [comment]
> ![2019-02-03 155032](https://user-images.githubusercontent.com/11220892/52174181-7073ea80-27cb-11e9-9e30-7fddec33950b.png)
> 
> @nzomkxia A new error has been encountered

Seems it's an unit test failure and I can reproduce it.
```
[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   ServiceControllerTest.shouldFilterUsingPattern:113
Expected: a collection with size <10>
     but: collection size was <4>
[ERROR]   ServiceControllerTest.shouldGetAllApplications:94
Expected: a collection with size <10>
     but: collection size was <0>
[ERROR]   ServiceControllerTest.shouldGetAllServices:75
Expected: a collection with size <10>
     but: collection size was <3>
[INFO]
[ERROR] Tests run: 45, Failures: 3, Errors: 0, Skipped: 0
```
Currently, you can skip it by `./mvnw clean package -Dskiptests`
I'll figure it out.

**Comment by biyuhao** [comment]
> ![2019-02-03 155032](https://user-images.githubusercontent.com/11220892/52174181-7073ea80-27cb-11e9-9e30-7fddec33950b.png)
> 
> @nzomkxia A new error has been encountered

Seems it's an unit test failure and I can reproduce it.
```
[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   ServiceControllerTest.shouldFilterUsingPattern:113
Expected: a collection with size <10>
     but: collection size was <4>
[ERROR]   ServiceControllerTest.shouldGetAllApplications:94
Expected: a collection with size <10>
     but: collection size was <0>
[ERROR]   ServiceControllerTest.shouldGetAllServices:75
Expected: a collection with size <10>
     but: collection size was <3>
[INFO]
[ERROR] Tests run: 45, Failures: 3, Errors: 0, Skipped: 0
```
Currently, you can skip it `./mvnw clean package -DskipTests` as a workaround.
I'll figure it out.

**Comment by SFlora** [comment]
@nzomkxia @biyuhao  
Thank you. Problem solved
