### ISSUE TITLE
service governance compatibility question

### ISSUE THREAD

**Issue by zhaixiaoxiang** [apache/incubator-dubbo-ops#296]
> Dubbo Admin只会按照Dubbo 2.7的格式去读取配置，因此所有在Admin上配置规则都可以读到，但是之前在注册中心上遗留的Dubbo 2.6格式的规则，不会展示在Dubbo Admin，也不能在Dubbo Admin上进行操作。

请问下, 新版Dubbo Admin不支持2.6格式的规则了? 那以前配置的很多治理规则怎么办?

**Comment by nzomkxia** [comment]
支持2.6格式的规则，在新版本Dubbo Admin写入规则的时候，会按照2.6的URL格式也向发送一份，但是不会去读取遗留的规则，这些规则依然会在2.6的客户端生效，只是不会在新版本的Dubbo Admin中展示。  
因为以前没有强制规定每个服务(Dubbo2.7中包括应用)只能配置一条规则，因此可能会存在一个服务有多条遗留的情况，不太方便在新版本的Dubbo Admin中作展示

**Comment by zhaixiaoxiang** [comment]
> 支持2.6格式的规则，在新版本Dubbo Admin写入规则的时候，会按照2.6的URL格式也向发送一份，但是不会去读取遗留的规则，这些规则依然会在2.6的客户端生效，只是不会在新版本的Dubbo Admin中展示。
> 因为以前没有强制规定每个服务(Dubbo2.7中包括应用)只能配置一条规则，因此可能会存在一个服务有多条遗留的情况，不太方便在新版本的Dubbo Admin中作展示

这样理解对不: 在新版Dubbo Admin上新建的规则对2.6和2.7的dubbo服务都会生效(因为生成了两种格式的), 原来的Dubbo Admin上的规则还是生效的, 只是在新版 Admin 上是不显示, 也不能修改. 只能手动迁移到新版Admin

**Comment by nzomkxia** [comment]
> > 支持2.6格式的规则，在新版本Dubbo Admin写入规则的时候，会按照2.6的URL格式也向发送一份，但是不会去读取遗留的规则，这些规则依然会在2.6的客户端生效，只是不会在新版本的Dubbo Admin中展示。
> > 因为以前没有强制规定每个服务(Dubbo2.7中包括应用)只能配置一条规则，因此可能会存在一个服务有多条遗留的情况，不太方便在新版本的Dubbo Admin中作展示
> 
> 这样理解对不: 在新版Dubbo Admin上新建的规则对2.6和2.7的dubbo服务都会生效(因为生成了两种格式的), 原来的Dubbo Admin上的规则还是生效的, 只是在新版 Admin 上是不显示, 也不能修改. 只能手动迁移到新版Admin

没错，只有一点：新版Dubbo Admin上只有服务级别的规则会生成2.6格式，应用级别的不会，因为Dubbo2.6中不存在应用级别的配置
