### ISSUE TITLE
根目录README上的dubbo的maven依赖容易误解

### ISSUE THREAD

**Issue by awayings** [apache/incubator-dubbo-ops#299]
![image](https://user-images.githubusercontent.com/688149/52758227-7925b580-3042-11e9-9788-4f7e80655e8d.png)

dubbo-parent的写法让人容易误解。这里应该是直接引入dubbo的包比较好

**Comment by nzomkxia** [comment]
请问是哪里？没有在README里面找到dubbo-parent的依赖

**Comment by awayings** [comment]
https://raw.githubusercontent.com/apache/incubator-dubbo/master/README.md 这个文件64行

**Comment by biyuhao** [comment]
> https://raw.githubusercontent.com/apache/incubator-dubbo/master/README.md 这个文件64行

本 repo 为 Dubbo控制台
该文件属于 https://github.com/apache/incubator-dubbo/ 项目(core framework)，如有需要请提 issue 或者 PR 给对应的 repo 😄
