### ISSUE TITLE
默认访问端口8080在哪里配置的?怎么修改?

### ISSUE THREAD

**Issue by gshkb** [apache/incubator-dubbo-ops#317]

**Comment by kezhenxu94** [comment]
@gshkb 可在 application.properties 中添加配置
```properties
server.port=8081
```
或者启动时指定参数 `-Dserver.port=8081`

**Comment by gshkb** [comment]
![image](https://user-images.githubusercontent.com/28503416/53216197-cd5a1680-368e-11e9-919b-fb887de2446a.png)
在vi dubbo-admin-ui/config/index.js 配置中修改路由设置

**Comment by kezhenxu94** [comment]
> ![image](https://user-images.githubusercontent.com/28503416/53216197-cd5a1680-368e-11e9-919b-fb887de2446a.png)
> 在vi dubbo-admin-ui/config/index.js 配置中修改路由设置

只有本地开发时才需要这个修改, 打包运行可以不改

**Comment by gshkb** [comment]
Thank you




| |
w99699w
邮箱：w99699w@126.com
|

Signature is customized by Netease Mail Master

在2019年02月22日 10:47，kezhenxu94 写道：


在vi dubbo-admin-ui/config/index.js 配置中修改路由设置

只有本地开发时才需要这个修改, 打包运行可以不改
