### ISSUE TITLE
服务查询页面可否加个分页功能？

### ISSUE THREAD

**Issue by zxbu** [apache/incubator-dubbo-ops#318]
如果有数千个接口的话，每次打开服务查询页面 
http://localhost:8080/#/service?filter=%2a&pattern=service
浏览器就会卡住一分钟左右

**Comment by nzomkxia** [comment]
好的，后续版本会加上服务端分页 @zxbu

**Comment by zxbu** [comment]
@nzomkxia 
我刚才又进一步确认了一下，2000左右条数据，后端接口返回的非常快，40-100ms，应该是前端渲染的性能导致的。
仅供分析

**Comment by nzomkxia** [comment]
> @nzomkxia
> 我刚才又进一步确认了一下，2000左右条数据，后端接口返回的非常快，40-100ms，应该是前端渲染的性能导致的。
> 仅供分析

好的，2000个服务非常多了，请问你们是在使用Dubbo2.7么？

**Comment by zxbu** [comment]
> > @nzomkxia
> > 我刚才又进一步确认了一下，2000左右条数据，后端接口返回的非常快，40-100ms，应该是前端渲染的性能导致的。
> > 仅供分析
> 
> 好的，2000个服务非常多了，请问你们是在使用Dubbo2.7么？

没有使用Dubbo2.7，使用的版本是Dubbo2.6.2

**Comment by kexianjun** [comment]
+1, 之前用最新的 Dubbo Admin 连接公司开发环境的注册中心，* 查询所有服务页面响应非常慢.
