### ISSUE TITLE
monitor没有图表，没有services菜单。

### ISSUE THREAD

**Issue by kingyoungfan** [apache/incubator-dubbo-ops#32]
<img width="1198" alt="wx20180529-153356 2x" src="https://user-images.githubusercontent.com/6263774/40644890-4225d87a-6357-11e8-83b8-2072d17b414c.png">

**Comment by kingyoungfan** [comment]
@chickenlj

**Comment by punmin** [comment]
@kingyoungfan  https://github.com/apache/incubator-dubbo-ops/pull/4

**Comment by JiakunXu** [comment]
试试 检查 dubbo-monitor-simple pom.xml dubbo 的版本 和 dubbo 服务的版本 是否一致

**Comment by kingwang317** [comment]
我也有一樣的問題POM跟服務的DUBBO版本也確認過一致了都是 2.5.10

**Comment by kingwang317** [comment]
我的問題已經解決了，請參考 #62

**Comment by htynkn** [comment]
Closing via #4
