### ISSUE TITLE
Test Method Fail on latest devlop branch with dubbo 2.7.0 

### ISSUE THREAD

**Issue by ettingshausen** [apache/incubator-dubbo-ops#322]
I run the [dubbo-registry-zookeeper-sample](https://github.com/apache/incubator-dubbo-spring-boot-project/tree/master/dubbo-spring-boot-samples/dubbo-registry-zookeeper-samples) code and follow the  [configuration specification](http://dubbo.apache.org/zh-cn/blog/dubbo-admin.html). 
The provider boot successful and listed in OPS service list. But test failed.
```
System Error, please try again later! Message:Failed to check the status of the service org.apache.dubbo.spring.boot.demo.consumer.DemoService:1.0.0. 
No provider available for the service org.apache.dubbo.spring.boot.demo.consumer.DemoService:1.0.0 from the url zookeeper://172.16.0.91:2181/org.apache.dubbo.registry.RegistryService?application=dubbo-admin&dubbo=2.0.2&generic=true&interface=org.apache.dubbo.spring.boot.demo.consumer.DemoService:1.0.0&pid=22124&register.ip=10.0.75.1&release=2.7.0&side=consumer&timestamp=1551095888498 to the consumer 10.0.75.1 use dubbo version 2.7.0
```
The provider config 
>```
>spring.application.name=dubbo-registry-zookeeper-provider-sample
>dubbo.scan.base-packages=org.apache.dubbo.spring.boot.demo.provider.service
>embedded.zookeeper.port = 2181
>dubbo.protocol.name=dubbo
>dubbo.protocol.port=20881
>dubbo.registry.address=zookeeper://172.16.0.91:${embedded.zookeeper.port}
>dubbo.metadata-report.address=zookeeper://172.16.0.91:2181
>demo.service.version=1.0.0
>```  
And the dubbo-admin config
>```
>admin.registry.address=zookeeper://127.0.0.1:2182
>admin.config-center=zookeeper://127.0.0.1:2182
>admin.metadata.address=zookeeper://127.0.0.1:2182
>```    

Additionally, in the [dubbo-admin doc](http://dubbo.apache.org/zh-cn/blog/dubbo-admin.html) `admin.metadata.address` different from `dubbo.metadata-report.address`.
 According to my attempt, I think it should be `admin.metadata.address` since there's no config metadata file provided.

**Comment by nzomkxia** [comment]
sorry for the late reply, I'll look into the service test Issue and the document mistake @ettingshausen

**Comment by ettingshausen** [comment]
@nzomkxia I just pull the latest code，now it works. I think the last commit fix this promblem.
Thank you.

**Comment by nzomkxia** [comment]
> @nzomkxia I just pull the latest code，now it works. I think the last commit fix this promblem.
> Thank you.

yes，the last commit fix a Service test issue, I'll look into the doc issue

**Comment by nzomkxia** [comment]
@ettingshausen I've changed the doc in website to `admin.metadata-report.address`, please wait for website update
