### ISSUE TITLE
windows node npm install 安装失败

### ISSUE THREAD

**Issue by boonyachengdu** [apache/incubator-dubbo-ops#327]
C:\Users\admin\Desktop\Dubbo\incubator-dubbo-ops\dubbo-admin-ui>npm install

> uglifyjs-webpack-plugin@0.4.6 postinstall C:\Users\admin\Desktop\Dubbo\incubator-dubbo-ops\dubbo-admin-ui\node_modules\webpack\node_modules\uglifyjs
-webpack-plugin
> node lib/post_install.js

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","ar
ch":"x64"})

added 1257 packages from 696 contributors and audited 12092 packages in 57.716s
found 0 vulnerabilities

C:\Users\admin\Desktop\Dubbo\incubator-dubbo-ops\dubbo-admin-ui>

**Comment by kezhenxu94** [comment]
@boonyachengdu 如果这有这两行 WARN 的话, 其实并非失败, 是正常的:

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","ar
ch":"x64"})

**Comment by boonyachengdu** [comment]
> @boonyachengdu 如果这有这两行 WARN 的话, 其实并非失败, 是正常的, 不影响:
> 
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","ar
> ch":"x64"})

C:\Users\boonya\Desktop\dubbo\incubator-dubbo-ops\dubbo-admin-ui>npm run dev

> dubbo-admin-ui@1.0.0 dev C:\Users\boonya\Desktop\dubbo\incubator-dubbo-ops\dubbo-admin-ui
> webpack-dev-server --inline --progress --config build/webpack.dev.conf.js

 13% building modules 30/60 modules 30 active ...components\public\notify\Snackbar.vue{ parser: "babylon" } is deprecated; we now treat it as { parser: "b 95% emitting

 WARNING  Compiled with 1 warnings                                                                              23:45:08

  ✘  http://eslint.org/docs/rules/semi  Extra semicolon
  src\components\ServiceSearch.vue:209:57
            const filter = this.$route.query.filter || '*';
                                                           ^


✘ 1 problem (1 error, 0 warnings)


Errors:
  1  http://eslint.org/docs/rules/semi

You may use special comments to disable some warnings.
Use // eslint-disable-next-line to ignore the next line.
Use /* eslint-disable */ to ignore all warnings in a file.

**Comment by boonyachengdu** [comment]
> @boonyachengdu 如果这有这两行 WARN 的话, 其实并非失败, 是正常的, 不影响:
> 
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","ar
> ch":"x64"})

没法正常跑啊

**Comment by kezhenxu94** [comment]
@boonyachengdu 这个只是代码风格的warning，启动完打开localhost:8080试试

**Comment by nzomkxia** [comment]
@boonyachengdu 这个问题不影响运行，我已经修复了

**Comment by kezhenxu94** [comment]
issue 先关闭了，如果还有问题可以再打开
