### ISSUE TITLE
dubbo-admin-2.0.0新增权重，页面报错

### ISSUE THREAD

**Issue by sunshinebaby00** [apache/incubator-dubbo-ops#35]
使用dubbo-admin-2.0.0新增一个权重的时候无法成功页面报错，可能是一个组件id设置有问题，下面是详细截图：
1. 新增权重：
![image](https://user-images.githubusercontent.com/9410296/41267430-0bededf6-6e2e-11e8-94f7-4c837a1f8107.png)

2. 点击保存报错
![image](https://user-images.githubusercontent.com/9410296/41267214-2511ff94-6e2d-11e8-8f9c-e527385c57b1.png)

3. 查看报错的代码
![image](https://user-images.githubusercontent.com/9410296/41267207-1c233d4e-6e2d-11e8-8df9-ee4bd396fdd5.png)
4. 查看页面，应该时服务名对应的元素id设置有问题
![image](https://user-images.githubusercontent.com/9410296/41267230-3f5538e4-6e2d-11e8-9c2e-c8607eb594be.png)

**Comment by nzomkxia** [comment]
please try the new dubbo ops
