### ISSUE TITLE
dubbo-admin<version>0.0.1-SNAPSHOT ???不应该是2点多？而且是war

### ISSUE THREAD

**Issue by haozx1997** [apache/incubator-dubbo-ops#41]
现在	 dubbo-admin的pom是这样的

<groupId>com.alibaba</groupId>
	<artifactId>dubbo-admin</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>jar</packaging>

还是 http://dubbo.apache.org/books/dubbo-admin-book/install/admin-console.html
这个网址应该更新了

**Comment by nzomkxia** [comment]
dubbo admin depends on spring boot now.  
thanks I'll update the admin console guide

**Comment by nzomkxia** [comment]
the doc has been updated
