### ISSUE TITLE
dubbo-admin.xml配置问题

### ISSUE THREAD

**Issue by giraffe8** [apache/incubator-dubbo-ops#45]
启动报错error：
org.springframework.beans.factory.parsing.BeanDefinitionParsingException: Configuration problem: Unable to locate Spring NamespaceHandler for XML schema namespace [http://dubbo.apache.org/schema/dubbo]
Offending resource: URL [file:/D:/idea_workspance/incubator-dubbo-ops/dubbo-admin/target/classes/dubbo-admin.xml]

解决办法：
dubbo-admin.xml的dubbo命令空间
http://dubbo.apache.org/schema/dubbo应该改为http://code.alibabatech.com/schema/dubbo

或者
<dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>dubbo</artifactId>
            <version>2.6.2</version>
        </dependency>
version改为2.6.2以上

**Comment by lovepoem** [comment]
I think upgrade the dubbo version to 2.6.2  is better

**Comment by giraffe8** [comment]
very good

**Comment by lovepoem** [comment]
Can you please send a PR?

**Comment by lovepoem** [comment]
close this via https://github.com/apache/incubator-dubbo-ops/pull/47

**Comment by chensiyuan0214** [comment]
成功解决了我的问题，提醒所有像我这样的小白们：
xmlns:dubbo="xxxxxxxxxxxxxx" 和 xsi:schemaLocation="xxxxxxxxxxxxxxxxxxxx"中你为dubbo所配的部分一定要一样。小白很容易东复制西复制就弄得一个是Apache的一个是Alibaba的了。
在国内的人最好用Alibaba的那个网址
在国外的人应该都能用

**Comment by Mike2017go** [comment]
still use the latest version 2.6.4 . It works;
