### ISSUE TITLE
查看服务详情报错

### ISSUE THREAD

**Issue by giraffe8** [apache/incubator-dubbo-ops#46]
地址：
http://localhost:7001/governance/services/com.tz.user.dubbo.CallCenterFacadeAPI/providers/1

错误信息：
Invocation of method 'getMessage' in class org.springframework.web.servlet.support.RequestContext threw exception org.springframework.context.NoSuchMessageException: No message found under code 'default.service.filter' for locale 'zh_CN'. at org/springframework/web/servlet/view/velocity/spring.vm[line 27, column 57]

**Comment by nzomkxia** [comment]
the i18n mapping failed, I'll fix it, thanks

**Comment by crazy6995** [comment]
the same error. 

```
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Tue Jun 26 10:19:59 CST 2018
There was an unexpected error (type=Internal Server Error, status=500).
Invocation of method 'getMessage' in class org.springframework.web.servlet.support.RequestContext threw exception org.springframework.context.NoSuchMessageException: No message found under code 'default.lazy' for locale 'zh_CN'. at org/springframework/web/servlet/view/velocity/spring.vm[line 27, column 57]
```

**Comment by htynkn** [comment]
Closing via help from #70. Could you try this with latest version?
