### ISSUE TITLE
No message found under code 'revision' for locale 'zh_CN'.

### ISSUE THREAD

**Issue by WywTed** [apache/incubator-dubbo-ops#58]
when i open the detail page of the service , there is a error like below:

org.springframework.context.NoSuchMessageException: No message found under code 'revision' for locale 'zh_CN'.
maybe there is something wrong in the i18n file. Please check it, thanks

**Comment by WywTed** [comment]
and i add revision=revision to the file message.properties , it becomes normal.

**Comment by yinghuzhu** [comment]
change line 81 in the templates/governance/screen/providers/show.vm
```
<th>#springMessage($entry.key):</th>
```
to
```
<th>#springMessageText($entry.key, $entry.key):</th>
```

that mean that the key is default value if there is no find the key in the message.properties

**Comment by htynkn** [comment]
Closing via help from #70. Could you verify this with latest version?

**Comment by WywTed** [comment]
@htynkn  ya, i have tryied and it works well, thanks
