### ISSUE TITLE
monitor can't see any services and applications

### ISSUE THREAD

**Issue by kingwang317** [apache/incubator-dubbo-ops#62]
As title 

My Zookeeper and Dubbo services all in the docker,  all services have self external ip with port

Please Help , thanks

<img width="1287" alt="screen shot 2018-07-04 at 6 23 21 pm" src="https://user-images.githubusercontent.com/2889511/42272058-8bfa4e1e-7fb7-11e8-8772-09b27699e823.png">

**Comment by jiaopy** [comment]
/dubbo-monitor-simple/src/main/resources/META-INF/dubbo/internal/com.alibaba.dubbo.container.Container 下修改
jetty-monitor=com.alibaba.dubbo.monitor.simple.container.JettyContainer
dubbo.properties下修改
dubbo.container=log4j,spring,registry,jetty-monitor
然后就好了

**Comment by kingwang317** [comment]
Hi @jiaopy  

Thanks, it's works!
