### ISSUE TITLE
dubbo-monitor-simple-ServletApi与jetty不兼容

### ISSUE THREAD

**Issue by fiyang** [apache/incubator-dubbo-ops#72]
jdk 1.8  macos
打包完成---启动报错。
class javax-serveletapi  not found.
将pom.xml里
 <dependency>
            <groupId>javax.servlet</groupId>
            <artifactId>javax.servlet-api</artifactId>
        </dependency>
scope去掉依然报错
class -javax.servlet.RequestDispatcher not found
将  pom.xml servlet  的api
原3.1.0升级为
<servlet_version>4.0.1</servlet_version>
问题解决
源码需要更新一下版本

**Comment by ralf0131** [comment]
Hi, could you please send a pull request?
