### ISSUE TITLE
可否根据应用名称或主机名将指定的应用的某个节点下线，进行发布?

### ISSUE THREAD

**Issue by shenhuaxx** [apache/incubator-dubbo-ops#76]
具体需求：
    进行自动发布的时候，通过http方式 将指定应用集群中的某一个节点下线，不会再有rpc请求过来，然后进行发布。
    循环上述操作，直到该应用的所有节点都重新发布成功。

dubbo admin 有没有后台接口可以针对应用节点下线？
如果没有，是否有比较优雅的扩展方式？

**Comment by yinghuzhu** [comment]
我们的做法是在dubbo-admin中扩展了http接口，下线时根据指定节点将该节点的服务全部禁用，上线时启用指定节点上所有服务

**Comment by shenhuaxx** [comment]
> 我们的做法是在dubbo-admin中扩展了http接口，下线时根据指定节点将该节点的服务全部禁用，上线时启用指定节点上所有服务

我也扩展了dubbo-admin的源码，在里面加了两个接口，解决需求。

**Comment by nzomkxia** [comment]
可以提个该功能的PR么？

**Comment by shenhuaxx** [comment]
> 可以提个该功能的PR么？

我是基于dangdang魔改的那一版做的扩展,而且那一版的dubbo-admin还是webx框架，估计不太适合提到这里来。
