### ISSUE TITLE
dubbo-monitor-simple部署后Charts乱码

### ISSUE THREAD

**Issue by soonway** [apache/incubator-dubbo-ops#78]
dubbo-monitor-simple-2.6.0部署到服务器配置好后可以启动，但是查看charts时图片上面除了曲线图正常显示外，其它有文字的地方都是乱码。
具体的我只是添加了一个log4j.properties文件，其它的都是按实际配置的。如下图所示：

![elapsed](https://user-images.githubusercontent.com/8384987/43393323-36982780-9429-11e8-8697-03b1115327f5.png)

**Comment by nzomkxia** [comment]
the dubbo monitor will be part of the new dubbo admin

**Comment by gaoyuear** [comment]
I came across the same issue on centos 7.2, solved by following the instruction of http://mscorefonts2.sourceforge.net/ that installed the missing font.

**Comment by soonway** [comment]
@gaoyuear thanks a lot.
