### ISSUE TITLE
克隆 master到本地， 然后进入admin目录 执行打包命令

### ISSUE THREAD

**Issue by malagebi** [apache/incubator-dubbo-ops#89]
克隆 master到本地， 然后进入admin目录 执行打包命令 报错：
com.alibaba.dubbo.common.utils不存在
com.alibaba.dubbo.common不存在
com.alibaba.dubbo.common.utils不存

**Comment by satansk** [comment]
@malagebi 能够提供下 Maven 版本和打包命令呢？
