### ISSUE TITLE
dubbo-admin禁用服务无效-（从incubator-dubbo-ops中获取的版本）

### ISSUE THREAD

**Issue by zhouhuashao** [apache/incubator-dubbo-ops#90]
dubbo-admin部署成功，禁用服务后，状态还是已启用，同时消费者还是可以访问该服务。
如果重启消费者应用，发现禁用有效，不能访问该服务，启用服务后，可以访问该服务。
看到的问题现象是：禁用服务，只有消费者应用重启后才能生效。不能动态控制。有没有大神帮忙看看是什么原因？谢谢。

**Comment by zonghaishang** [comment]
这个是dubbo的Bug，我会修复

**Comment by beiwei30** [comment]
这个功能算是 **推空保护**。你这个例子里应该只有一个服务端，禁用之后地址列表为空，dubbo 拒绝这样的地址更新，不然线上直接跌零了。

**Comment by zonghaishang** [comment]
我在邮件回复了，可以在dubbo-ops里面控制，目前是可以禁用的，但是不生效。

**Comment by zonghaishang** [comment]
close it now, see: https://github.com/apache/incubator-dubbo-ops/issues/177
