### ISSUE TITLE
dubbo admin能看到提供者，看不到消费者

### ISSUE THREAD

**Issue by zhblxm** [apache/incubator-dubbo-ops#98]
导入工程，启动后。能看到提供者，无法看到消费者。服务可以正常调用，为啥呢？

**Comment by fulihu2008** [comment]
我的也是

**Comment by chensl5566** [comment]
后台查询逻辑存在问题，路径/api/service/detail的后台方法不应该将配置的application作为条件查询，
因为消费者和生产者所配置的applicatioin名称不一样，
将org.apache.dubbo.admin.controller.ServiceController文件的serviceDetail方法中providerService.findByAppandService(app, service)改成providerService.findByService(service)，
同时将consumerService.findByAppandService(app, service)改成consumerService.findByService(service)即可正常显示。

**Comment by nzomkxia** [comment]
fixed

**Comment by chinajoe** [comment]
说一下我遇到的问题与解决办法。
背景：dubbo admin上只能看到提供者，看不到消费者，但是zookeeper上可以看到既有提供者也有消费者。

**1. provider配置如下：**
`
dubbo.application.name=test
dubbo.registry.timeout=40000
dubbo.registry.address=zookeeper://127.0.0.1:2181
dubbo.metadata-report.address=zookeeper://127.0.0.1:2181
dubbo.protocol.name=dubbo
dubbo.protocol.port=20887
dubbo.provider.loadbalance=leastactive
dubbo.provider.timeout=30000
dubbo.provider.version=1.0
`

**2. consumer配置如下：**
`
dubbo.application.name=test
dubbo.registry.address=zookeeper://127.0.0.1:2181
dubbo.metadata-report.address=zookeeper://127.0.0.1:2181
dubbo.consumer.version=*
`
**定位问题**
dubbo admin获取consumers的方法如下图：
![image](https://user-images.githubusercontent.com/16307708/105192326-f0d7b580-5b72-11eb-8cb4-c046197c7281.png)
最终调取方法如下：
![image](https://user-images.githubusercontent.com/16307708/105192504-22e91780-5b73-11eb-8f1d-a49e8574d0ab.png)

urls存储的格式：<com.xxx.Service:*,something>, 而s=com.xxx.Service:1.0
所以导致获取不到consumer的信息。

**解决方法**
修改consumer的版本：
`dubbo.consumer.version=1.0`
